require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FollowerProductsController do

  # This should return the minimal set of attributes required to create a valid
  # FollowerProduct. As you add validations to FollowerProduct, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all follower_products as @follower_products" do
      follower_product = FollowerProduct.create! valid_attributes
      get :index
      assigns(:follower_products).should eq([follower_product])
    end
  end

  describe "GET show" do
    it "assigns the requested follower_product as @follower_product" do
      follower_product = FollowerProduct.create! valid_attributes
      get :show, :id => follower_product.id.to_s
      assigns(:follower_product).should eq(follower_product)
    end
  end

  describe "GET new" do
    it "assigns a new follower_product as @follower_product" do
      get :new
      assigns(:follower_product).should be_a_new(FollowerProduct)
    end
  end

  describe "GET edit" do
    it "assigns the requested follower_product as @follower_product" do
      follower_product = FollowerProduct.create! valid_attributes
      get :edit, :id => follower_product.id.to_s
      assigns(:follower_product).should eq(follower_product)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FollowerProduct" do
        expect {
          post :create, :follower_product => valid_attributes
        }.to change(FollowerProduct, :count).by(1)
      end

      it "assigns a newly created follower_product as @follower_product" do
        post :create, :follower_product => valid_attributes
        assigns(:follower_product).should be_a(FollowerProduct)
        assigns(:follower_product).should be_persisted
      end

      it "redirects to the created follower_product" do
        post :create, :follower_product => valid_attributes
        response.should redirect_to(FollowerProduct.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved follower_product as @follower_product" do
        # Trigger the behavior that occurs when invalid params are submitted
        FollowerProduct.any_instance.stub(:save).and_return(false)
        post :create, :follower_product => {}
        assigns(:follower_product).should be_a_new(FollowerProduct)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FollowerProduct.any_instance.stub(:save).and_return(false)
        post :create, :follower_product => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested follower_product" do
        follower_product = FollowerProduct.create! valid_attributes
        # Assuming there are no other follower_products in the database, this
        # specifies that the FollowerProduct created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FollowerProduct.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => follower_product.id, :follower_product => {'these' => 'params'}
      end

      it "assigns the requested follower_product as @follower_product" do
        follower_product = FollowerProduct.create! valid_attributes
        put :update, :id => follower_product.id, :follower_product => valid_attributes
        assigns(:follower_product).should eq(follower_product)
      end

      it "redirects to the follower_product" do
        follower_product = FollowerProduct.create! valid_attributes
        put :update, :id => follower_product.id, :follower_product => valid_attributes
        response.should redirect_to(follower_product)
      end
    end

    describe "with invalid params" do
      it "assigns the follower_product as @follower_product" do
        follower_product = FollowerProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FollowerProduct.any_instance.stub(:save).and_return(false)
        put :update, :id => follower_product.id.to_s, :follower_product => {}
        assigns(:follower_product).should eq(follower_product)
      end

      it "re-renders the 'edit' template" do
        follower_product = FollowerProduct.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FollowerProduct.any_instance.stub(:save).and_return(false)
        put :update, :id => follower_product.id.to_s, :follower_product => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested follower_product" do
      follower_product = FollowerProduct.create! valid_attributes
      expect {
        delete :destroy, :id => follower_product.id.to_s
      }.to change(FollowerProduct, :count).by(-1)
    end

    it "redirects to the follower_products list" do
      follower_product = FollowerProduct.create! valid_attributes
      delete :destroy, :id => follower_product.id.to_s
      response.should redirect_to(follower_products_url)
    end
  end

end
